version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - progresDB:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379'
    volumes:
      - redisDB:/data
volumes:
  progresDB:
  redisDB: